from aiogram.fsm.state import State, StatesGroup

class QuestionnaireStates(StatesGroup):
    ConfirmRules = State()
    Q1_FullName = State()
    Q2_BirthDate = State()
    Q3_Gender = State()
    Q4_PhoneNumber = State()
    Q5_TelegramUsername = State()
    Q6_Region = State()
    Q7_WhoApplies = State()
    Q8_SaboPatient = State()
    Q9_HowFound = State()
    Q10_HasDiagnosis = State()
    Q11_DiagnosisText = State()
    Q12_DiagnosisFile = State()
    Q13_Complaint = State()
    Q14_MainDiscomfort = State()
    Q14_MainDiscomfortOther = State()
    Q15_ImprovementsAfterTreatment = State()
    Q16_WithoutTreatmentConsequences = State()
    Q17_NeedConfirmationDocs = State()
    Q17_ConfirmationFile = State()
    Q18_AvgIncome = State()
    Q18_IncomeDoc = State()
    Q19_ChildrenCount = State()
    Q19_ChildrenDocs = State()
    Q21_FamilyWork = State() 
    Q22_HousingType = State()
    Q22_HousingDoc = State()
    Q23_Contribution = State()
    Q24_AdditionalFile = State()
    Q25_FinalComment = State()